# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SlTitVsYX2HM6mghn4xJGu4vx78VurOi
"""

from google.colab import drive
drive.mount('/content/drive')

from PIL import Image, ImageDraw, ImageFont
import os
os.system("python -m pip install Pillow")
import smtplib 
from email.mime.multipart import MIMEMultipart 
from email.mime.text import MIMEText 
from email.mime.base import MIMEBase 
from email import encoders
import csv 


# enter the credentials
fromaddr = "codearts.ieee@ncuindia.edu"
password = "codearts@2020"

s = smtplib.SMTP('smtp.gmail.com', 587)
s.starttls()
s.login("codearts.ieee@ncuindia.edu","codearts@2020"
)


#enter the path of csv file
csvfile = r"/content/drive/MyDrive/WinnerList.csv"

def process(word,toaddr):
    image = Image.open("/content/drive/MyDrive/top5.jpg")
    draw = ImageDraw.Draw(image)
    font = ImageFont.truetype("/content/drive/My Drive/times-new-roman.ttf",30)
    try:
        os.mkdir('certificates')
    except:pass
    #enter the co-ordinates 
    (x, y) = (615, 455)
    color = 'rgb(0, 0, 0)'
    draw.text((x, y), word.title(), fill=color, size=100, font=font)
    filename = os.path.join('certificates',f"{word}_certificate.pdf")
    image.save(os.path.join(filename))
    msg = MIMEMultipart() 
    msg['From'] = fromaddr 
    msg['To'] = toaddr 
    msg['Subject'] = "Certificates Of NCU Codathon"
    body = """Dear 
Thank you for participating in NCU Codathon. PLease find the attached certificate of yours below. Your cash prize will be sent soon. Our team will call you on your registered mobile number.

Regards,
Code Arts





 """
    msg.attach(MIMEText(body, 'plain')) 
    attachment = open(filename, "rb")  
    p = MIMEBase('application', 'octet-stream') 
    p.set_payload((attachment).read()) 
    encoders.encode_base64(p) 
    p.add_header('Content-Disposition', "attachment; filename= %s" % filename) 
    msg.attach(p) 
    text = msg.as_string()
    s.sendmail(fromaddr, toaddr, text)

with open(csvfile,'r') as file:
    print('processing pls wait')
    for word,email in [x for x in csv.reader(file)][1:]:
        process(word,email)
    print('certificates sent')
s.quit()

